### ISSUE TITLE
请问对象带泛型类如何Json序列化

### ISSUE THREAD

**Issue by Ellio007** [LuodiJackShen/AutoJson#1]
如下：
class Test < T > {
  List < T >  list;
}

**Comment by Ellio007** [comment]
如下：
class Test <T>{
List<T>  list;
}

**Comment by LuodiJackShen** [comment]
抱歉，刚看到。无论是json_serialiazable还是jaguar_serializer，目前没找到加范型的方法。一个替代方案是使用继承，但是不太优雅。
