### ISSUE TITLE
android studio  2021.3.1 can not use

### ISSUE THREAD

**Issue by nEdAy** [LuodiJackShen/AutoJson#11]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/10076735/191671483-92a8d9c3-3327-497a-a06c-a4ac7bc0d1cf.png">

Android Studio Dolphin | 2021.3.1
Build #AI-213.7172.25.2113.9014738, built on September 1, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    documentation.show.toolbar=true

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    idea.plugin.protoeditor (213.6461.28)
    com.robohorse.robopojogenerator (2.3.7)
    com.ankit.mahadik.json.dart.class (2.15)
    cn.neday.excavator (2.2.0)
    cn.deemons.tinypng.plugin (2.3)
    Dart (213.7371)
    com.shenyong.flutter.refgenerator (1.1.0)
    io.flutter (70.0.3)

**Comment by LuodiJackShen** [comment]
这个早就升级了，你再看下
