### ISSUE TITLE
Android Studio 2022.2.1 can not use

### ISSUE THREAD

**Issue by c-reschke** [LuodiJackShen/AutoJson#12]
![image](https://user-images.githubusercontent.com/6054359/234605765-712fb6a8-76a8-4d95-bc9e-d6a3b45a6ce6.png)

![image](https://user-images.githubusercontent.com/6054359/234605912-07a557e9-47b7-4c90-b001-3586747c1423.png)

Thanks

**Comment by LuodiJackShen** [comment]
JetBrains is reviewing this update.

**Comment by LuodiJackShen** [comment]
> JetBrains is reviewing this update.

The latest version has been approved and the version number is 3.7-IU-222.4459.24
