### ISSUE TITLE
toJson()方法写法错误！

### ISSUE THREAD

**Issue by azhengyongqin** [LuodiJackShen/AutoJson#3]
### `toJson()`方法写法错误，会造成 `jsonEncode(user)` 这样的用法报错！
使用对象时错误如下：
```dart
User user = new User("夏目友人帐",'1023007219@qq.com');
print(jsonEncode(user));
```
![image](https://user-images.githubusercontent.com/18138282/57944248-f80fe000-7908-11e9-9bcd-115c77255dfc.png)

使用插件自动生产的 `toJson()`代码如下：
```dart
Map<String, dynamic> toJson(User instance) => _$UserToJson(instance);
```
应该改为：
```dart
Map<String, dynamic> toJson() => _$UserToJson(this);
```

**Comment by LuodiJackShen** [comment]
感谢提醒，这个估计是json_seriliazble升级导致的，现已经修复了，请升级到1.5版本。
