### ISSUE TITLE
Android studio 更新至2021.1.1版本后，插件新版本不可用，marketplace中版本为1.5

### ISSUE THREAD

**Issue by lzw-sdu** [LuodiJackShen/AutoJson#8]
更新Android studio后，插件不可用，市场中下载为1.5版本，下载新版本包离线安装会报错与当前IDE版本不匹配
Error
Plugin 'AutoJson' (version '3.1-lU-203.7717.56')
is not compatible with the current version of the
IDE, because it requires build 203.* or older but
the current build is Al-211.7628.21

**Comment by LuodiJackShen** [comment]
给我留个适配的时间。。。

**Comment by LuodiJackShen** [comment]
已经提交最新版本：3.2-IU-211.7628.21，审核通过后可以更新使用

**Comment by lzw-sdu** [comment]
作者大大太强了，辛苦辛苦～
